### ISSUE TITLE
出牌 API 參數的設計

### ISSUE THREAD

**Issue by qrtt1** [Game-as-a-Service/LoveLetter#16]
![Image](https://user-images.githubusercontent.com/193223/203937805-925f5ad4-5d08-425a-b66a-f6bbc06866b4.png)

不同的卡片需要的 `出牌` 參數是不同的

## 參型式整理

1. 衛兵： `對手` `打算猜測的手牌名稱` 
2. 神父： `對手`
3. 男爵：`對手`
4. 侍女：(無參數)
5. 王子：`對手`
6. 國王：`對手`
7. 伯爵夫人：(無參數)
8. 公主：(無參數)

## 分類 1

對應至 PR #15 實作的 

```py
class CardAction(BaseModel):
    turn_player: str
    opponent: str
    card_action: List[str]
```

建議改寫

```py
class GuessCardAction(BaseModel):
    turn_player: str
    opponent: str
    turn_player_card: str
    guess_card: str
```

* 衛兵： `對手` `打算猜測的手牌名稱` 

## 分類 2

可能的實作：

```py
class DoSomethingAction(BaseModel):
    turn_player: str
    opponent: str
    turn_player_card: str
```

* 神父： `對手`
* 男爵：`對手`
* 王子：`對手`
* 國王：`對手`

## 分類 3

可能的實作：

```py
class UseCardAction(BaseModel):
    turn_player: str
    turn_player_card: str
```

* 侍女：(無參數)
* 伯爵夫人：(無參數)
* 公主：(無參數)

**Comment by s9891326** [comment]
感覺可以用這個當作基底，其他特殊的輸入參數用繼承的方式來實作

- 基底
```python
class UseCardAction(BaseModel):
    turn_player: str
    turn_player_card: str
```

- 繼承
```python
class DoSomethingAction(UseCardAction):
    opponent: str
```

**Comment by qrtt1** [comment]
> 感覺可以用這個當作基底，其他特殊的輸入參數用繼承的方式來實作
> 
> * 基底
> 
> ```python
> class UseCardAction(BaseModel):
>     turn_player: str
>     turn_player_card: str
> ```
> 
> * 繼承
> 
> ```python
> class DoSomethingAction(UseCardAction):
>     opponent: str
> ```

經你這麼一提： `turn_player` 與 `turn_player_card` 是 required parameters 被凸顯出來，也許該放回 URI 的 path variables。想起一下新的分類參數，會變成：

### 分類 1 

```py
class GuessCard(BaseModel):
    opponent: str
    guess_card: str
```

### 分類 2

```py
class ToSomeoneCard(BaseModel):
    opponent: str
```

### 分類 3

什麼都不用傳

**Comment by s9891326** [comment]
> > 感覺可以用這個當作基底，其他特殊的輸入參數用繼承的方式來實作
> > 
> > * 基底
> > 
> > ```python
> > class UseCardAction(BaseModel):
> >     turn_player: str
> >     turn_player_card: str
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * 繼承
> > 
> > ```python
> > class DoSomethingAction(UseCardAction):
> >     opponent: str
> > ```
> 
> 經你這麼一提： `turn_player` 與 `turn_player_card` 是 required parameters 被凸顯出來，也許該放回 URI 的 path variables。想起一下新的分類參數，會變成：
> 
> ### 分類 1
> ```python
> class GuessCard(BaseModel):
>     opponent: str
>     guess_card: str
> ```
> 
> ### 分類 2
> ```python
> class ToSomeoneCard(BaseModel):
>     opponent: str
> ```
> 
> ### 分類 3
> 什麼都不用傳

恩~ 有理 就只是我們的endpoint會漏漏長而已XD
