### ISSUE TITLE
[TDD] 經過了一回合後，侍女的保護失效

### ISSUE THREAD

**Issue by qrtt1** [Game-as-a-Service/LoveLetter#28]
由於 #5 關於 `侍女` 的進度已經完成，可以開始實作保護失效的情境了。

這次不同於單純的 `Player` 捨棄卡片獲得保護的情境，得牽連至 `Game` 與 `Round` 的連結。
確保在經過一回合後，失去侍女保護的玩家，可以被弄死或被做些什麼。

**Comment by qrtt1** [comment]
由於 #5 關於 `侍女` 的進度已經完成，可以開始實作保護失效的情境了。

這次不同於單純的 `Player` 捨棄卡片獲得保護的情境，得牽連至 `Game` 與 `Round` 的連結。
確保在經過一回合後，失去侍女保護的玩家，可以被弄死或被做些什麼。

**Comment by s9891326** [comment]
- #33 一起實作
