### ISSUE TITLE
[TDD] 遊戲結束規則

### ISSUE THREAD

**Issue by qrtt1** [Game-as-a-Service/LoveLetter#41]
#19 完工後，已經具備 `play` 的行為可以正常進行遊戲，也可以正常結束一局。

經過若干局後，遊戲可以達到結束的條件，就應該讓遊戲結束，並宣佈最終贏家。

<img src="https://user-images.githubusercontent.com/193223/206603815-c489c2fd-fcbc-47da-98da-6a63162f95d1.png" height="300" />

**Comment by s9891326** [comment]
這感覺可以拆一拆 大家分著作~

- [ ] 玩家開始遊戲，遊戲結束後手牌大小一樣，比較丟棄牌數值總和大小
- [ ] 最後的勝負判斷。依照不同的參加人數，所需的好感指示物也不一樣，達到對應的好感指示物就結束此遊戲，`追求公主成功`

**Comment by qrtt1** [comment]
@s9891326 嘿啊，只要還沒有人認的票都歡迎喊聲撿去做呦。

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/193223/206685901-883fd7c6-97d4-443f-ac27-1d2d94f4730b.png">

對應到 `玩家已出牌` (**play** method) 後的動作：
* 下一位玩家 (做了)
* 開新一局 (做了)
* 結束遊戲 (這張票要做)

https://github.com/Game-as-a-Service/LoveLetter/blob/8d33850a646d6c912c06333cf5c32adae065e4d4/love_letter/models/__init__.py#L118-L146

出牌後的動作是對應在這幾行之後

https://github.com/Game-as-a-Service/LoveLetter/blob/8d33850a646d6c912c06333cf5c32adae065e4d4/love_letter/models/__init__.py#L124-L132
