### ISSUE TITLE
[player-context] 手牌的使用方法

### ISSUE THREAD

**Issue by qrtt1** [Game-as-a-Service/LoveLetter#51]
接續著 #46 

玩家可知道自己手上的手牌有哪些，但牌的用法並沒有具體寫在 `狀態上`。

需參考 #16 與相關的遊戲規則，在卡片上追加使用方法。好讓 client 端能替使用者創造出合理的 UI/UX

## 需思考的內容

玩家在操作介面上

* 能選擇這張卡嗎？
* 選了卡片後，是可以直接丟棄的卡片嗎？
* 選了卡片後，需要指定 Player 的清單是什麼？清單包含玩家本人嗎？
* 選了卡片後，需要指定 Player 的清單是什麼？清單包含玩家本人嗎？需要再指定卡片嗎？有哪些卡片可以指定？

**Comment by s9891326** [comment]
1. 能選擇這張卡嗎？
    - 玩家A 持有 `王子` or `國王`、`伯爵夫人`，提示只能打出`伯爵夫人`
    - `仕女、公主`沒有出牌限制
2.  選了卡片後，需要指定 Player 的清單？
    - player只有對手們的: `神父、男爵、國王`
    - player對手 + 自己: `王子`
3. 選了卡片後，需要指定 Player 的清單？ 需要再指定卡片嗎？
    - `衛兵`: player只有對手們、需要再指定除了衛兵以外的牌
